<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-04-10T11:56:29+05:30" hostname="https://curious-wolf-5cvo28-dev-ed.my.salesforce.com" tests="1" failures="1"  errors="0"  time="0.27">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Apr 10, 2020 11:56 AM"/>
            <property name="testExecutionTime" value="0.27 s"/>
            <property name="testTotalTime" value="0.27 s"/>
            <property name="commandTime" value="4.75 s"/>
            <property name="hostname" value="https://curious-wolf-5cvo28-dev-ed.my.salesforce.com"/>
            <property name="orgId" value="00D2w000003zXUDEA2"/>
            <property name="username" value="rahul.das@curious-wolf-5cvo28.com"/>
            <property name="testRunId" value="7072w00000Kn6iq"/>
            <property name="userId" value="0052w000002vVGlAAM"/>
        </properties>
        <testcase name="fourCasesTodayAccount" classname="MaxCasesTest" time="0.27">
            <failure message="System.AssertException: Assertion Failed: case status same as updated case status: Expected: Closed, Actual: New"><![CDATA[Class.MaxCasesTest.fourCasesTodayAccount: line 62, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
